### ISSUE TITLE
2021.1 compatibility

### ISSUE THREAD

**Issue by Vampire** [Hinaser/gfm-advanced#14]
Same as #6, you again have defined a max version and so your plugin cannot be used on 2021.1. :-(

**Comment by Hinaser** [comment]
Hi
In my recognition, max version is always required.
I'll try to unset max version.

**Comment by Hinaser** [comment]
I removed `until-version` property from plugin configuration.
Hope you won't be required to wait for plugin update every time you update IDE.

### change log
https://github.com/Hinaser/gfm-advanced/compare/v0.0.5...v0.0.6

I've just submitted version 0.0.6 to JetBrains.
Plugin update will be delivered to you soon.

**Comment by Hinaser** [comment]
gfm-advanced 0.0.6 is now in public.
Close this issue.

**Comment by Vampire** [comment]
Seems your hope is not fulfulled: https://plugins.jetbrains.com/plugin/14683-gfma/versions
![grafik](https://user-images.githubusercontent.com/325196/114015997-ac52e080-986a-11eb-909b-a7d111f4429b.png)
But there are plugins without upper bound, so it should be possible

**Comment by Hinaser** [comment]
Hi, thanks for reporting.
Could you suggest the plugin you mentioned which doesn't have upper bound.
I'll look its source code if it is publicly available.

**Comment by Vampire** [comment]
Most plugins I have installed. Only a handful breaks due to upper version bound. Just to name a random one: "Open With"

**Comment by Hinaser** [comment]
Thanks to your great help, I finally managed to unset upper version limitation.

![finally-itsdone](https://user-images.githubusercontent.com/12316730/114062173-308c7e80-98d2-11eb-8853-fbb5266e70e0.png)

Version 0.0.7 will be available soon after JetBrains approve it.
