### ISSUE TITLE
2020.3 compatibility

### ISSUE THREAD

**Issue by Vampire** [Hinaser/gfm-advanced#6]
Your plugin currently is marked as only being compatible with 2020.2.
Can you please make it compatible with 2020.3 and / or open up the compatibility setting?

**Comment by Hinaser** [comment]
Thank you to notify. Really thanks.
I didn't know that this plugin hasn't been working on 2020.3.

I'll investigate the issue.

**Comment by Hinaser** [comment]
Dealing this issue with https://github.com/Hinaser/gfm-advanced/issues/5

**Comment by Hinaser** [comment]
I've just submit 2020.3 compatible version of this plugin.
As soon as JetBrains approves it, you can install/update.
Thank you for reporting the issue!

**Comment by Hinaser** [comment]
https://plugins.jetbrains.com/plugin/14683-gfma
v0.0.4 is now available!
Closing.

**Comment by Vampire** [comment]
Great, thanks.
Will report some nits next, now that I can see the plugin. :-)
