### ISSUE TITLE
Probably wrong tooltip on "User Github Markdown API"

### ISSUE THREAD

**Issue by Vampire** [Hinaser/gfm-advanced#8]
This looks like the checkbox was once called "Render offline" and wasn't adapted when the option was changed:
![grafik](https://user-images.githubusercontent.com/325196/105255555-1620ef80-5b84-11eb-887d-822fbe914f30.png)

**Comment by Hinaser** [comment]
Thanks!
I'll check this in my code and modify soon.

**Comment by Hinaser** [comment]
https://github.com/Hinaser/gfm-advanced/compare/v0.0.5
Fixed in v0.0.5 and waiting JetBrains to approve it.
I'll let you know when new plugin is ready.

**Comment by Hinaser** [comment]
v0.0.5 released!
closing.
