### ISSUE TITLE
Github => GitHub

### ISSUE THREAD

**Issue by Vampire** [Hinaser/gfm-advanced#9]
You everywhere use Github, but it is called GitHub :-)

**Comment by Hinaser** [comment]
Ok, I'll see to it.
Thanks for reporting!

**Comment by Hinaser** [comment]
https://github.com/Hinaser/gfm-advanced/compare/v0.0.5
Fixed in v0.0.5 and waiting JetBrains to approve it.
I'll let you know when new plugin is ready.

**Comment by Hinaser** [comment]
v0.0.5 released!
closing.
